(in-package #:photo-ai-lisp/tests)

(in-suite photo-ai-lisp-tests)

;;; UT1 — unit tests for src/proc.lisp
;;; Tests struct accessors, platform dispatch, spawn lifecycle.
;;; Process-spawning tests skip on Windows (cmd.exe exits too quickly).

(test proc-struct-accessors-exist
  "Accessor functions generated by defstruct must be bound."
  (is-true (fboundp 'photo-ai-lisp::child-process-p)
           "child-process-p predicate should exist")
  (is-true (fboundp 'photo-ai-lisp::child-process-process)
           "child-process-process accessor should exist")
  (is-true (fboundp 'photo-ai-lisp::child-process-stdin)
           "child-process-stdin accessor should exist")
  (is-true (fboundp 'photo-ai-lisp::child-process-stdout)
           "child-process-stdout accessor should exist"))

(test proc-default-argv-platform
  "%default-argv should return the platform-appropriate command.
   On Windows we prefer tools/conpty-bridge/conpty-bridge.exe when built
   (wraps cmd.exe in a real ConPTY so interactive CLIs work); if the
   bridge binary isn't present we fall back to plain cmd.exe."
  (let ((argv (photo-ai-lisp::%default-argv)))
    (is-true (listp argv)
             "%default-argv should return a list, got: ~s" argv)
    (is-true (stringp (first argv))
             "first element of argv should be a string, got: ~s" (first argv))
    (cond
      ((not (uiop:os-windows-p))
       (is (string= "/bin/bash" (first argv))
           "Unix default should be /bin/bash, got: ~s" (first argv)))
      ((uiop:file-exists-p photo-ai-lisp::*conpty-bridge-path*)
       (is-true (search "conpty-bridge" (first argv))
                "Windows with bridge present should spawn the bridge, got: ~s"
                (first argv))
       (is (string= "cmd.exe" (second argv))
           "Bridge should be passed cmd.exe as its argument, got: ~s"
           (second argv)))
      (t
       (is (string= "cmd.exe" (first argv))
           "Windows without bridge should spawn cmd.exe, got: ~s"
           (first argv))))))

(test proc-spawn-child-returns-child-process
  "spawn-child should return a child-process struct."
  (if (uiop:os-windows-p)
      (skip "proc-spawn-child-returns-child-process: skipped on Windows")
      (let ((child (photo-ai-lisp::spawn-child '("/bin/bash" "-c" "sleep 0.2"))))
        (unwind-protect
            (is-true (typep child 'photo-ai-lisp::child-process)
                     "spawn-child should return a child-process, got: ~s"
                     (type-of child))
          (photo-ai-lisp::kill-child child)))))

(test proc-accessor-stream-types
  "child-process-stdin must be a writable stream; stdout a readable stream."
  (if (uiop:os-windows-p)
      (skip "proc-accessor-stream-types: skipped on Windows")
      (let ((child (photo-ai-lisp::spawn-child '("/bin/bash" "-c" "sleep 0.2"))))
        (unwind-protect
            (progn
              (is-true (output-stream-p (photo-ai-lisp::child-process-stdin child))
                       "child-process-stdin should be an output (writable) stream")
              (is-true (input-stream-p (photo-ai-lisp::child-process-stdout child))
                       "child-process-stdout should be an input (readable) stream"))
          (photo-ai-lisp::kill-child child)))))

(test proc-process-slot-non-nil
  "The process slot must hold a non-nil uiop process-info after spawn."
  (if (uiop:os-windows-p)
      (skip "proc-process-slot-non-nil: skipped on Windows")
      (let ((child (photo-ai-lisp::spawn-child '("/bin/bash" "-c" "sleep 0.2"))))
        (unwind-protect
            (is-true (photo-ai-lisp::child-process-process child)
                     "child-process-process slot should be non-nil after spawn")
          (photo-ai-lisp::kill-child child)))))

(test proc-child-alive-lifecycle
  "child-alive-p should be true after spawn and false after kill."
  (if (uiop:os-windows-p)
      (skip "proc-child-alive-lifecycle: skipped on Windows")
      (let ((child (photo-ai-lisp::spawn-child '("/bin/bash" "-c" "sleep 5"))))
        (is-true (photo-ai-lisp::child-alive-p child)
                 "child should be alive immediately after spawn")
        (photo-ai-lisp::kill-child child)
        (sleep 0.15)
        (is (not (photo-ai-lisp::child-alive-p child))
            "child should not be alive after kill-child"))))
