;;; AUTO-GENERATED by POST /api/presets  (method DEPLOY).
;;; Live snapshot of *presets* at deploy time. Re-running DEPLOY
;;; rewrites this file in full. Delete to fall back to the
;;; factory bundle in presets.lisp.

(in-package #:photo-ai-lisp)

(clrhash *presets*)
(setf *preset-order* '())

(defpreset "claude"
  :argv (list "claude" "--dangerously-skip-permissions")
  :agent "claude"
  :group "起動"
  :input nil)

(defpreset "gemini"
  :argv (list "gemini")
  :agent "gemini"
  :group "起動"
  :input nil)

(defpreset "codex"
  :argv (list "codex")
  :agent "codex"
  :group "起動"
  :input nil)

(defpreset "学習"
  :agent "claude"
  :group nil
  :input "photo-reference-build スキルで GT (Excel 一覧 + PDF 写真帳) から reference.json を逆生成しろ。
- ref に出現してマスタに無い語は検索パターン候補としてユーザーに提示して追記の可否を確認しろ
- GT パス / 既存マスタ / 出力先が不明なら chat で聞け、推測で進めるな")

(defpreset "施工状況"
  :agent "claude"
  :group "解析"
  :input "写真区分=施工状況 のバイアスで photo-ai-workflow 全段 (scan → keyword-extract → match-master → report-export) を回せ。施工状況以外の区分が混じったら個別に確認しろ。
- 対象ディレクトリ / 参照マスタ / 種別 / 出力先が不明なら chat で聞け
- マスタ未選択なら「マスタ確認 preset で先に」と案内")

(defpreset "出来形管理"
  :agent "claude"
  :group "解析"
  :input "写真区分=出来形管理 のバイアスで photo-ai-workflow 全段を回せ。寸法/出来形値の写り込みを優先で読み、出来形以外の写真は別群に分離しろ。
- 対象ディレクトリ / 参照マスタ / 種別 / 出力先が不明なら chat で聞け
- マスタ未選択なら「マスタ確認 preset で先に」と案内")

(defpreset "品質管理"
  :agent "claude"
  :group "解析"
  :input "写真区分=品質管理 のバイアスで photo-ai-workflow 全段を回せ。温度管理黒板を検出したら photo-temperature-cycle-resolve で 9 枚サイクルを解決してから match-master 結果を上書きしろ。
- 対象ディレクトリ / 参照マスタ / 種別 / 出力先が不明なら chat で聞け
- マスタ未選択なら「マスタ確認 preset で先に」と案内")

(defpreset "その他"
  :agent "claude"
  :group "解析"
  :input "写真区分のバイアスを掛けず photo-ai-workflow 全段 (AI 抽出 + 決定論判定) を回せ。区分は AI 出力と decisive ルールの合議で決めろ。
- 対象ディレクトリ / 参照マスタ / 種別 / 出力先が不明なら chat で聞け
- マスタ未選択なら「マスタ確認 preset で先に」と案内")

(defpreset "マスタ確認"
  :agent "claude"
  :group nil
  :input "解析を始める前のドライラン役として動け。
1. masters/ 配下の CSV/Excel を列挙しろ
2. 各マスタを行数・写真区分内訳・種別 top-N でプロファイルしろ
3. ユーザーに「今日の現場で使うマスタはどれか」を選ばせろ
4. 選ばれたマスタを写真区分 × 種別で絞り込み、該当する全行を列挙しろ
5. ギャップ (区分/種別の欠落) を発見したら「学習 preset でマスタを育てて」と案内しろ
連結ツリー整合などの健全性チェックには踏み込むな。あくまで「どのマスタで解析を始めるか」の合意形成だけが役割だ。")

(defpreset "マスタ棚卸し"
  :agent "claude"
  :group nil
  :input "masters/ を機械的に棚卸ししろ。以下のコマンドを順に実行し、結果の転記だけが仕事だ。推論・探索・健全性チェックは禁止。

1. Bash `ls -la masters/` で実在ファイルを確認
2. Bash `find . -maxdepth 4 -type f \\( -name '*.csv' -o -name '*.xlsx' -o -name '*.xls' \\) -not -path '*/node_modules/*' -not -path '*/.git/*' -not -path '*/target/*'` でリポジトリ全体のマスタ候補を列挙
3. 各候補に Bash `file <path>; wc -l <path>` を回し encoding と行数を確定
4. CSV は Read で先頭 20 行まで開き、1 行目をスキーマとして抜き出せ
5. Markdown テーブル (path | rows | format | header) で 1 枚にまとめ、末尾に期待カラム (写真区分 / 種別) を持たないマスタをギャップとして列挙
6. ユーザーに「このマスタで進めるか、学習 preset で育てるか」を 1 行で問え")

(defpreset "写真帳 pdf"
  :argv (list "%USERPROFILE%\\photo-ai-go\\photo-ai.exe" "export" "pdf" "result.json")
  :group "出力"
  :input nil)

(defpreset "写真帳 excel"
  :argv (list "%USERPROFILE%\\photo-ai-go\\photo-ai.exe" "export" "excel" "result.json")
  :group "出力"
  :input nil)

(defpreset "画面クリア"
  :argv (list "/exit")
  :group nil
  :input "cls")

